Fix test case for ERC20 interest farm due to unstable timing
Error was:

  1) ERC20 Interest Farm
       should check staking reward:

      AssertionError: expected 601000000000000000000n to equal 600000000000000000001n
      + expected - actual

      -601000000000000000000n
      +600000000000000000001n