Add test case to catch rare error due to leftover POW5 dust
Error was:

  1) Bureau 4: Reverse Repo
       should withdraw LP-SFT from YieldHarvest after POW5 loan is repaid:
     Error: VM Exception while processing transaction: reverted with reason string 'NOPOW5 must be 0'